### ISSUE TITLE
is there are way to time interval?

### ISSUE THREAD

**Issue by yunchiri** [Team-Picky/flutter_datetime_picker_plus#5]
I want use 

``` 
showDateTimePicker
```

with minute inteval only ( 00, 30) 

is there are easy way?

thanks library

**Comment by freakness** [comment]
Hi @yunchiri,

You could achieve this by using `showPicker` instead and creating a custom PickerModel 

```
class MyPickerModel extends CommonPickerModel {
...
}
```
I think it is possible to implement your use case this way. You can take some inspiration from `Time12hPickerModel` which limits the hours to the [0,11] interval.  And `TimePickerModel` which can hide the seconds column.

**Comment by yunchiri** [comment]
Thanks! have good day 👍
