### ISSUE TITLE
Year - Month mode

### ISSUE THREAD

**Issue by Poem7200** [Team-Picky/flutter_datetime_picker_plus#7]
Sometimes I just want to pick year and month, or even just year, but I can just pick Year-Month-Date.

If the current version have already solved this problem, please tell me the way to realize things mentioned above, or just show an example.

**Comment by freakness** [comment]
Hi @Poem7200,

Take a look at the source code for TimePickerModel [here](https://github.com/Team-Picky/flutter_datetime_picker_plus/blob/982a9e121b14278c1c1f2f3c1c6790b670d04920/lib/src/date_model.dart#L378). This model has an option to disable the seconds column. You can create your own model as explained in [this comment](https://github.com/Team-Picky/flutter_datetime_picker_plus/issues/5#issuecomment-2061625162). 

Regards
